### ISSUE TITLE
Bad method call in ext/math.js

### ISSUE THREAD

**Issue by jsobus-neurosys** [TriumphLLC/Blend4Web#10]
Hi,

In ext/math.js there is an import that looks like this:

```
/**
 * Set the parametric line initial point.
 * @method module:math.set_pline_point
 * @param {ParametricLine} pline Parametric line.
 * @param {Vec3} vec3 Point.
 */
exports.set_pline_initial_point = m_math.set_pline_initial_point;
```

So in JSDoc i see that this function has a name of "set_pline_point" and it is used like that in whole file. The problem is that there is no such a function because in exports You set it name to "set_pline_initial_point". Remember to change function names also in documentation and other calls of this function when do a refactor like this ;)

**Comment by jsobus-neurosys** [comment]
Just to be clear - some of your library code calls to bad name action what gives an error.

**Comment by EvgenyRodygin** [comment]
Hi,

We've fixed this JsDoc part in the last release (16.09). So thanks for pointing it out.

**Comment by jsobus-neurosys** [comment]
The problem was not a JsDoc but the other code is calling this wrong name method. This gives exceptions in apps.

**Comment by EvgenyRodygin** [comment]
Actually, we haven't.
I've just fixed that. Our bad. Thank you one more time.
