### ISSUE TITLE
B4W ERROR: Object Selection is not available on the scene (Fullscreen HMD Mode, Android Mobile)

### ISSUE THREAD

**Issue by vingkan** [TriumphLLC/Blend4Web#13]
We are developing a VR game using Blend4Web, based off of the structure of the Space Disaster example. When playing in Fullscreen HMD Mode on an Android device, we are not able to select objects using the Scenes API. The error message reads: `"B4W ERROR: Object Selection is not available on the scene"`

The error traceback led to: objects.js:1712 > scenes.js:4305, this function:
```javascript
exports.pick_color = function(scene, canvas_x, canvas_y) {
   var subs_color_pick = get_subs(scene, m_subs.COLOR_PICKING);
   if (subs_color_pick) {
       // NOTE: rewrite camera.proj_matrix and camera.view_proj_matrix
       // restoring not needed
       var canvas = m_cont.get_canvas();
       var h = canvas.clientHeight;
       var w = canvas.clientWidth;
       m_cam.set_color_pick_proj(subs_color_pick.camera, canvas_x, canvas_y, w, h);

       // NOTE: may be some delay since exports.update() execution
       m_prerender.prerender_subs(subs_color_pick, subs_color_pick.camera);
       if (subs_color_pick.do_render)
           m_render.draw(subs_color_pick);

       var subs_color_pick_xray = get_subs(scene, m_subs.COLOR_PICKING_XRAY);
       if (subs_color_pick_xray) {
           m_mat4.copy(subs_color_pick.camera.proj_matrix,
                   subs_color_pick_xray.camera.proj_matrix);
           m_mat4.copy(subs_color_pick.camera.view_proj_matrix,
                   subs_color_pick_xray.camera.view_proj_matrix)
           m_util.extract_frustum_planes(
                   subs_color_pick_xray.camera.view_proj_matrix,
                   subs_color_pick_xray.camera.frustum_planes);
           m_prerender.prerender_subs(subs_color_pick_xray, subs_color_pick_xray.camera);
           if (subs_color_pick_xray.do_render)
               m_render.draw(subs_color_pick_xray);
       }

       if (subs_color_pick.do_render ||
               subs_color_pick_xray && subs_color_pick_xray.do_render)
           return m_render.read_pixels(subs_color_pick_xray?
                   subs_color_pick_xray.camera.framebuffer:
                   subs_color_pick.camera.framebuffer, 0, 0);
       else
           return null;
   } else
       m_print.error("Object Selection is not available on the scene");

   return null;
}
```

The author of [this post](https://www.blend4web.com/ru/forums/topic/1348/) seemed to be having a similar problem, but was able to fix the problem by setting Object Selection = ON (instead of AUTO) in Blender. This did not fix the problem for us.

What does the `getsubs()` method do and is there anything we can do to make sure it returns a value in HMD mode?

**Comment by D504** [comment]
Hello.
pick_color is based on rendering color scene (each object has its own color). In VR there are 2 eyes which have different positions, project matrices. So we disable color picking in VR mode.

You can't use pick_color right now in this way. It is better use physics [ray tracing](https://www.blend4web.com/apps/code_snippets/code_snippets.html?scene=raytest).

**Comment by D504** [comment]
We are going to add the scenes.pick_center function, that renders the color scene and return an object in the viewport center.

I think it solve you issue.

**Comment by nederland074** [comment]
Implemented as a pick_center API function in the scenes.js module.
