### ISSUE TITLE
Blender Add-On - Normal Editor

### ISSUE THREAD

**Issue by mviranyi** [TriumphLLC/Blend4Web#14]
Is there a way to read the currently selected vertex's normal vector values?

Selecting an normal and trying to adapt only one axis (e.g. Z) does not work because on selection the normal vector isn't set to the current state in the UI.

**Comment by dalduba** [comment]
Unfortunately the current Blender event system doesn't allow you to handle vertex selection.
Hope that GSOC 2017 will bring to Blender new powerful and complete normal editing tools https://wiki.blender.org/index.php/User:RohanRathi/GSoC_2017/Proposal
