### ISSUE TITLE
Cycles IES lighting support within Blend4Web?

### ISSUE THREAD

**Issue by clessley** [TriumphLLC/Blend4Web#16]
My scene uses actual .ies files (lighting data) within the Cycles engine, specifically this: `https://gist.github.com/AngryLoki/4364512`

How to use this data with blen4web correctly?

I can see the lamp data within 3D object wireframe view however, upon export to html or json all lighting appears to default to the regular Blender engine using spot, sun, etc.

Please advise.

**Comment by konstantinkhomyakov3d** [comment]
Area lights are not supported in blend4web for now. Using arbitrary shape area lights in real-time engines is not trivial and is a hot topic nowadays. I think we'll also investigate this task in the future.

For now baking those lights is the right way for you :)

**Comment by YuriKovelenov** [comment]
Discussed on the forums https://www.blend4web.com/en/forums/topic/3360/
