### ISSUE TITLE
Building HTML doesn't minify correctly

### ISSUE THREAD

**Issue by AttilaVM** [TriumphLLC/Blend4Web#17]
Building a project does not remove line breaks from HTML, but substitutes them with spaces, which will not make the code smaller.

Example:

`<!DOCTYPE html> <html> <head> <title>Blessed</title> <meta charset="utf-8"> <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width"> <link type="text/css" rel="stylesheet" href="blessed.min.css?v=19042018172614"> <script type="text/javascript" src="./b4w.simple.min.js?v=19042018172614"></script> <script type="text/javascript" src="lib/blessed.min.js?v=19042018172614"></script> <script type="text/javascript" src="blessed.min.js?v=19042018172614"></script> </head> <body> <div id="main_canvas_container"></div> </body> </html>`

The expected result is:

`<!DOCTYPE html><html><head><title>Blessed</title><meta charset="utf-8"><meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width"><link type="text/css" rel="stylesheet" href="blessed.min.css?v=19042018172614"><script type="text/javascript" src="./b4w.simple.min.js?v=19042018172614"></script><script type="text/javascript" src="lib/blessed.min.js?v=19042018172614"></script><script type="text/javascript" src="blessed.min.js?v=19042018172614"></script></head><body><div id="main_canvas_container"></div></body></html>`

I use [pug](https://pugjs.org/api/getting-started.html), so it should not be a problem, except the deployer (???) remove my linked scripts if the input HTML is minified.

My Blend4Web version is 17.12.0

**Comment by dalduba** [comment]
Thanks for the report! Will check the issue.

**Comment by dalduba** [comment]
Fixed. Will be available in 18.05 Release Candidate.
