### ISSUE TITLE
Missing a license file

### ISSUE THREAD

**Issue by cwebber** [TriumphLLC/Blend4Web#2]
https://www.blend4web.com/en/downloads/ says that this application is released under the GPL, but I don't see any license file (or copyright headers, but the license file is even more important).  Could you add https://www.gnu.org/licenses/gpl-3.0.txt as COPYING.txt to your repository?

Thanks!

**Comment by alexkowel** [comment]
Hi. The licence file is actually here under https://github.com/TriumphLLC/Blend4Web/blob/master/license/GPL-license.txt
